### PR TITLE
Updating prim names

### LINKED ISSUE #1: Fix the naming of the primitives to be consistent with skywater-pdk format.
There is a spreadsheet @ [GF180MCU (GlobalFoundries 180nm PDK) -- Primitive Model Naming](https://docs.google.com/spreadsheets/d/1G88IhyqXGVu-BgH8hA-_N2YQnNiyPoPEqvXSOzmOaaY/edit#gid=1803291424) which is tracking what the new naming scheme should be.

### PR DESCRIPTION
**Pull request by FaragElsayed2**
Fixes https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/issues/1

-  Renaming all primitives with its new name except resistors.

### CODE REVIEW

**Review by atorkmabrains — APPROVED** [review]
I have reviewed the changes and approve it for merge.

**Comment by RTimothyEdwards** [comment]
When is this going to be done for the 9t library?  And is there a list of name translations somewhere?

**Comment by mithro** [comment]
The mapping can be found @ https://bit.ly/gf180mcu-names

I believe @atorkmabrains has a complete mapping.

**Review by mithro — APPROVED** [review]
LGTM

**Comment by RTimothyEdwards** [comment]
@mithro :  FYI, the document is incomplete as it does not reflect all process variants;  There must be metal4, 5, and 6 resistors and the top metal resistor depends on the variant's definition of top metal (which can be anything from metal3 to metal6).

I note that the resistors have not been changed and the name translations are marked with question marks.  Will this be resolved promptly?

**Pull request merged**
