### PR TITLE
Fixes buffer resizing for PnR tools

### LINKED ISSUE #2339: Resizer unable to optimize fanout for GF180 PDK
Testing `aes` design with GF180 PDK through `OpenLane` flow.
Using `OpenROAD 4174c3ad802d2ac1d04d387d2c4b883903f6647e`

`resizer.log`
```
===========================================================================
report_checks -path_delay max (Setup)
============================================================================
Startpoint: reset_n (input port clocked by clk)
Endpoint: _38075_ (recovery check against rising-edge clock clk)
Path Group: **async_default**
Path Type: max

Fanout     Cap    Slew   Delay    Time   Description
-----------------------------------------------------------------------------
                  0.15    0.00    0.00   clock clk (rise edge)
                          0.00    0.00   clock network delay (ideal)
                         10.00   10.00 ^ input external delay
                  1.15    0.64   10.64 ^ reset_n (in)
     1    0.05                           reset_n (net)
                  1.15    0.00   10.64 ^ input10/I (gf180mcu_fd_sc_mcu7t5v0__buf_20)
                  0.83    0.72   11.36 ^ input10/Z (gf180mcu_fd_sc_mcu7t5v0__buf_20)
    86    0.72                           net10 (net)
                  0.87    0.09   11.45 ^ load_slew88/I (gf180mcu_fd_sc_mcu7t5v0__buf_20)
                  1.56    1.10   12.55 ^ load_slew88/Z (gf180mcu_fd_sc_mcu7t5v0__buf_20)
   179    1.36                           net88 (net)
                  1.58    0.10   12.65 ^ load_slew87/I (gf180mcu_fd_sc_mcu7t5v0__buf_20)
                  2.09    1.39   14.04 ^ load_slew87/Z (gf180mcu_fd_sc_mcu7t5v0__buf_20)
   236    1.87                           net87 (net)
                  2.12    0.14   14.17 ^ load_slew85/I (gf180mcu_fd_sc_mcu7t5v0__buf_20)
                  2.09    1.49   15.66 ^ load_slew85/Z (gf180mcu_fd_sc_mcu7t5v0__buf_20)
   236    1.80                           net85 (net)
                  2.11    0.12   15.77 ^ load_slew84/I (gf180mcu_fd_sc_mcu7t5v0__buf_20)
                  1.62    1.19   16.96 ^ load_slew84/Z (gf180mcu_fd_sc_mcu7t5v0__buf_20)
   185    1.40                           net84 (net)
                  1.63    0.04   17.00 ^ load_slew83/I (gf180mcu_fd_sc_mcu7t5v0__buf_20)
                  1.77    1.23   18.23 ^ load_slew83/Z (gf180mcu_fd_sc_mcu7t5v0__buf_20)
   210    1.55                           net83 (net)
                  1.90    0.28   18.51 ^ _38075_/RN (gf180mcu_fd_sc_mcu7t5v0__dffrnq_1)
                                 18.51   data arrival time

                  0.15   50.00   50.00   clock clk (rise edge)
                          0.00   50.00   clock network delay (ideal)
                         -0.25   49.75   clock uncertainty
                          0.00   49.75   clock reconvergence pessimism
                                 49.75 ^ _38075_/CLK (gf180mcu_fd_sc_mcu7t5v0__dffrnq_1)
                          0.00   49.75   library recovery time
                                 49.75   data required time
-----------------------------------------------------------------------------
                                 49.75   data required time
                                -18.51   data arrival time
-----------------------------------------------------------------------------
                                 31.24   slack (MET)
````
Test case: 
[issue_reproducible.zip](https://github.com/The-OpenROAD-Project/OpenROAD/files/9724859/issue_reproducible.zip)

### PR DESCRIPTION
**Pull request by QuantamHD**
Fixes https://github.com/The-OpenROAD-Project/OpenROAD/issues/2339

Fixes [The-OpenROAD-Project/OpenROAD#2339](https://github.com/The-OpenROAD-Project/OpenROAD/issues/2339)

> It's a good idea to open an issue first for discussion.

- [  x ] Tests pass
- [ x  ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by QuantamHD** [comment]
@antonblanchard Is this the right fix for https://github.com/The-OpenROAD-Project/OpenROAD/issues/2339?

**Comment by QuantamHD** [comment]
@proppy Heads up

**Comment by proppy** [comment]
Does it also fix https://github.com/google/gf180mcu-pdk/issues/81 ?

**Comment by proppy** [comment]
Do we need the equivalent change for https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_sc_mcu9t5v0 ?

**Comment by antonblanchard** [comment]
> @antonblanchard Is this the right fix for [The-OpenROAD-Project/OpenROAD#2339](https://github.com/The-OpenROAD-Project/OpenROAD/issues/2339)?

Yes it looks right to me.

**Comment by antonblanchard** [comment]
> Do we need the equivalent change for https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_sc_mcu9t5v0 ?

Yes, it does need the same fix.

**Pull request merged**
