### PR TITLE
Adding missing user defined primitives.

### PR DESCRIPTION
**Pull request by mithro**
Signed-off-by: Tim 'mithro' Ansell <tansell@google.com>

### CODE REVIEW

**Review by RTimothyEdwards — APPROVED** [review]
This looks good to me.

**Comment by mithro** [comment]
There **_really_** should be;
 * Tests for the UDP modules
 * A CI to test that this works with various tooling

Both related to https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_sc_mcu7t5v0/issues/4

**Comment by mithro** [comment]
(I'm not going to block merging this pull request on those however.)

**Comment by QuantamHD** [comment]
LGTM

**Review by QuantamHD — APPROVED** [review]

**Comment by mithro** [comment]
Related change on the 9t cell library -> https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_sc_mcu9t5v0/pull/20

**Pull request merged**
